-- Insert sample properties for demonstration
INSERT INTO properties (
  title,
  description,
  price,
  type,
  property_type,
  bedrooms,
  bathrooms,
  area,
  address,
  city,
  state,
  featured,
  images
) VALUES
(
  'Apartamento Luxuoso em Área Nobre',
  'Magnífico apartamento com acabamento premium, vista panorâmica da cidade, 3 suítes amplas com closet, living integrado com varanda gourmet, 2 vagas de garagem. Condomínio completo com piscina, academia, salão de festas e segurança 24h.',
  1850000.00,
  'sale',
  'apartment',
  3,
  4,
  180.00,
  'Av. Principal, 1500',
  'São Paulo',
  'SP',
  true,
  ARRAY['/placeholder.svg?height=600&width=800', '/placeholder.svg?height=600&width=800', '/placeholder.svg?height=600&width=800']
),
(
  'Casa Moderna com Piscina',
  'Belíssima casa em condomínio fechado, projeto arquitetônico moderno, 4 suítes, escritório, piscina aquecida, área gourmet completa, jardim paisagístico. Localização privilegiada com fácil acesso.',
  3200000.00,
  'sale',
  'house',
  4,
  5,
  350.00,
  'Rua das Flores, 245',
  'São Paulo',
  'SP',
  true,
  ARRAY['/placeholder.svg?height=600&width=800', '/placeholder.svg?height=600&width=800', '/placeholder.svg?height=600&width=800']
),
(
  'Cobertura Duplex Premium',
  'Cobertura exclusiva com 2 andares, terraço privativo com piscina, churrasqueira e vista 360°, 4 suítes master, home theater, adega climatizada. O mais alto padrão de acabamento.',
  5800000.00,
  'sale',
  'penthouse',
  4,
  6,
  420.00,
  'Av. Beira Mar, 2800',
  'Rio de Janeiro',
  'RJ',
  true,
  ARRAY['/placeholder.svg?height=600&width=800', '/placeholder.svg?height=600&width=800', '/placeholder.svg?height=600&width=800']
),
(
  'Apartamento Compacto Centro',
  'Apartamento bem localizado no centro, 2 quartos, sala, cozinha americana, 1 vaga. Ideal para investimento ou primeiro imóvel. Próximo ao metrô e comércio.',
  4500.00,
  'rent',
  'apartment',
  2,
  2,
  65.00,
  'Rua Central, 890',
  'São Paulo',
  'SP',
  false,
  ARRAY['/placeholder.svg?height=600&width=800', '/placeholder.svg?height=600&width=800']
),
(
  'Sala Comercial Corporate',
  'Sala comercial em edifício corporativo classe A, 3 salas privativas, recepção, copa, 2 banheiros. Infraestrutura completa, ar condicionado central, 4 vagas.',
  12000.00,
  'rent',
  'commercial',
  0,
  2,
  120.00,
  'Av. Paulista, 3500',
  'São Paulo',
  'SP',
  false,
  ARRAY['/placeholder.svg?height=600&width=800', '/placeholder.svg?height=600&width=800']
),
(
  'Casa Confortável em Bairro Residencial',
  'Casa aconchegante, 3 quartos sendo 1 suíte, quintal amplo, garagem para 2 carros. Bairro tranquilo e familiar, próximo a escolas e supermercados.',
  6800.00,
  'rent',
  'house',
  3,
  3,
  200.00,
  'Rua das Acácias, 567',
  'Curitiba',
  'PR',
  false,
  ARRAY['/placeholder.svg?height=600&width=800', '/placeholder.svg?height=600&width=800']
);
